### ISSUE TITLE
Callout Elements

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#111]
While working on blockquote (#67), I needed to create a "callout"-style blockquote that would be floated either to the left or the right and have a smaller width.

An example can be seen here:
https://github.com/ucla/WebBlocks/blob/master/template/entity/blockquote/-ex-img-callout.png

It's likely that other elements will have similar needs. There are two basic issues to address here:
1. How do we set the width of these elements?
2. How do we establish when (at which breakpoint) these elements should flip to a 100% version for smaller viewports?

Following this line of questions, should "callout" be separated out into its own CSS class that could be generically applied to other elements? (e.g., a captioned image)

**Comment by jeffpignataro** [comment]
The example you have there is about 30% the width of the outer container. That seems like a pretty good way to define it. Of course we can use pixel width instead of a percentage, but if we always assume that it's going to be 30% of it's parent then I think that would work pretty well.

As you get to the small viewport sizes, I imagine these element would not be displayed? Or at least would end up as full width elements?

**Comment by alicetseng** [comment]
Hi @loganfranken. 
Can we just leverage the nested grid span class to handled the width? I think that's a more robust approach rather than setting a width directly on the blockquote element. So you can have something like:

```
<blockquote class="span3">  
```

Not every user wants a blockquote set at 30% -- some may want it set at 60% hence 

```
<blockquote class="span6"> 
```

Yet, 30% is a safe default. If we handle the default width and the responsive behavior as an extension of the grid so for example blockquote[class*="span"] { has some special settings for nested grid children that are blockquote entities} -- we can cover the broadest cases and not risk setting an assumption of the layout that the end-user cannot decide for for themself. 

I'm stongly in favor of us not setting explicit widths directly on content entities and allowing the grid do the width setting and such the responsive behaviors. I can send out an example of what I mean.

**Comment by jeffpignataro** [comment]
That's an excellent idea. I think this dovetails with the grid system discussion in [#113](https://github.com/ucla/WebBlocks/issues/113). But, I think this would be the most appropriate and flexible system to allow the user to determine the size of the element and manage the responsive layout of the element.

**Comment by alicetseng** [comment]
I agree we need to finish up the grid system  #113 . I have blocked time in my calendar this weekend to start posting some ideas. I do believe that having the responsive defaults and grid elements set up would really simplify the development of a lot of these entities -- as usually, placement/layout is the biggest challenge from the css perspective.

**Comment by alicetseng** [comment]
Sorry it's in email form- but I don't know how to attach a zip file as a Git comment.

Here's my very rough example in code {note the names are not semantic} as this is just a demo proto I've been working
on for our team (code is still somewhat hacky too). But, this should serve as enough to illustrate the idea of leveraging the grid for default widths and
responsive behaviors and how the end user can make simple choices once they understand the classes in the grid.

Basically — the reason I am so concerned we leave children elements width/layout agnogstic (from the entity perspective)— is for the specific business use case
we have for our sites. We have a large CMS where our end-users need to be able to easily decide the layouts for themselves.
If we bind specific layout settings to the elements — then we who support the CMS would need to pull out those settings.
I'd highly prefer we leave layout to a modular grid system and thus — we can drop and extend the grid settings as needed.

-alice

**Comment by loganfranken** [comment]
I thought @atsengucla made a good argument for why this should just plug into the grid system. I thought of potentially mixing in one of the grid widths into the `.callout` to specify a grid-based width, but it seemed like there were too many moving pieces in that scenario (how do we know that there's room for that many panels? what if it the designer wants a smaller or larger callout width? etc.)

I just went ahead and left `.callout` as a simple style alternative for `blockquote` (and updated the corresponding documentation to make this distinction clear). We may want to continue to use the term "callout" to specify this type of element throughout the framework but I'm not seeing a need to make it a generic component in the technical sense.

With that, I'm closing this issue. Thank you for the wonderful input, @atsengucla and @jeffpignataro!
