### ISSUE TITLE
Labels and Badges

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#122]
Bootstrap provides labels and badges:

``` html
<span class="label">Default</span>
<span class="badge">1</span>
```

I'm unsure from a usability perspective really what the difference is - because I could use either of these to accomplish either functionality. Is there a common name that is covered for both? This is something I'll go look at some other frameworks on and then propose a strategy.

As a note, these will automatically support all of the color controls that we've defined in our color strategy #109.

**Comment by ebollens** [comment]
I'm inclined to go with only:

``` html
<span class="badge">...</span>
```

The reason for this is because `.label` is the same name as an HTML element (`label`) but packs a different meaning. Anyone have an issue with this? @loganfranken @atsengucla @ccheung

**Comment by loganfranken** [comment]
I agree with you that the use of the term "label" is somewhat confusing/inappropriate since it has nothing to do with the identically-named `label` element. However, it looks like Foundation also uses this name (http://foundation.zurb.com/docs/elements.php), so we may be fighting against a convention.

As for the usability difference between the two, I would argue there's a difference (at least in how I've been using them):

#### Labels

I use labels for in-line notices. For example:

``` html
<span class="label label-important">Warning!</span> Do not drink the poison.
```

``` html
<span class="label label-info">Pro Tip</span> Use keyboard shortcuts.
```

#### Badges

In contrast, I only use badges to indicate to the User a quantity of something. For example, I recently used them within a navigation tab to show a User how many pending changes they had on that tab.

Really, I think they are just supposed to be Bootstrap's answer to those tiny numerical indicators that are so hot these days (for example, the little red numbers in Facebook) and that's why they get the increased `border-radius` (to make them appear as much like a circular icon as possible).

I'm not a fan of either "label" or "badge" but I'm not coming up with any great alternatives, so I'd be inclined to just roll with those names.

**Comment by ebollens** [comment]
@loganfranken any interest in working on this while I refactor the builder in #130? I'm moving this back to 1.0.04 since it's slipped this one (given that I was at Educause all of this week).

**Comment by loganfranken** [comment]
@ebollens Sounds good. Reassigning to me.

**Comment by loganfranken** [comment]
Spent some quality time with a thesaurus to try and drum up alternative names for labels and badges. Here's the list:
https://github.com/ucla/WebBlocks/wiki/Entity-Labels-and-Badges

I'm leaning towards "notice" for "label" and "indicator" for "badge" (it's a less hip, but more descriptive name IMO).

Thoughts?

@ebollens @atsengucla @ccheung 

Moving to 0.1.05 pending a discussion about this (tomorrow?)

**Comment by ebollens** [comment]
I think notice is too close to message, confusing the use cases. I don't like overloading `label` with two meanings (one for class and one for element), but what would you think about using badge for both types and then descriptive qualifiers to separate what label and badge presentationally? Honestly, even if the display is different, the semantic meaning feels very much the same in my book.

**Comment by loganfranken** [comment]
Based on today's meeting, I'm going to start developing badge (using the name, "badge").

**Comment by loganfranken** [comment]
Leaving this open until both Badge and Label (or equivalent entities) have been implemented. Moving to next milestone
