### ISSUE TITLE
Color Palette for WebBlocks Core

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#124]
@atsengucla would you be willing to take up the task of defining the hex values for the WebBlocks color palette? 

We will almost certainly have to define them a bit differently for UCLA, but it would be nice to have a default set for when people initially download WebBlocks - right now, I'm mostly using the Bootstrap values, but where there weren't any, I either winged something or just duplicated from elsewhere. You can find all the color settings in `/src/core/adapter/base/_variables.scss` with the prefix `$color`.

It would be nice to get someone else's feedback to make sure that I did these in a way that is reasonable to work with and also to catch any bugs that may crop up. As a note, `-foreground-text` is for those elements that are `.[color].text` whereas the `-background-` elements are used for when there is no `text` class on the element and the background is being specified. As a note, I'm already aware of a bug with the border color when you are working with the Bootstrap adapter (precedence order).

Also, to preview them, compile WebBlocks (minimally calling `rake _build_css`) and then check out the file `/demo/base/color.html`. You might also find `/demo/entity/button.html` and `/demo/entity/table.html` useful.

**Comment by alicetseng** [comment]
Sure. I have time scheduled this week for WebBlocks. I can get to this task this Friday- does that work for you?

**Comment by ebollens** [comment]
Yeah, that definitely works. It's no rush on this - not a critical thing like getting masthead CSS stuff defined - but rather just something we need at some point before launch. Figure it's probably more fun though than coding a ton of CSS ;)

**Comment by alicetseng** [comment]
@ebollens -- quick check in on this task. digging through the file to wrap my head around the logic but I'm a little fuzzy on what the overall scheme is. Can you clarify for me? For example what is the function of the foreground and background settings for text colors? Is this an information hierarchy thing? When I see background/foreground my first instinct is to think foreground values for text and background for box backgrounds -- but this is just me. So thought I'd check in with you first. Do you mean that the background-text is actually the background color for the text box? Thanks -- this will help me select appropriate colors if I get a better handle of the intended context.

**Comment by ebollens** [comment]
@atsengucla a good way to get a feel for it is actually just change a set for one and see what happens in `/demo/base/color.html`. However, the naming scheme I used follows this convention:
- Background is considered the default application of color
- `.text` says to instead color the font and leave the background alone

This decision was made for performance reasons (see the initial ticket on implementation issues).

Here's the breakdown of modifiers...

For the straight background, we get:

``` css
.info:not(.text) {
    color: $color-mood-info-background-text;
    background-color: $color-mood-info-background-shadow;
    border-color: $color-mood-info-border;
    text-shadow: $color-mood-info-background-text-shadow;
}
```

When you have a gradient, it is additionally:

``` css
.info.gradient:not(.text) {
    @include background-image(linear-gradient($color-mood-default-background, 
                                              $color-mood-default-background-shadow));
}
```

When you have light, it becomes:

``` css
.info.light:not(.text) {
    color: $color-mood-info-background-light-text;
    background-color: $color-mood-info-background-light-shadow;
    border-color: $color-mood-info-border;
    text-shadow: $color-mood-info-background-light-text-shadow;
}
```

When it is set for text, it is instead:

``` css
.info.text {
    color: $color-mood-success-foreground-text;
}
```

I'd be fine with changing the variable names if you don't like them though. Just give me guidance as to what they should be.

**Comment by alicetseng** [comment]
Update milestone for color. Have other projects but have scheduled time in 2 weeks to finish this off. Moved to 1.03.

**Comment by ebollens** [comment]
This has been moved to milestone 0.1.04.

**Comment by ebollens** [comment]
This has been moved to milestone 0.1.06.

**Comment by alicetseng** [comment]
Quick Update: started working on this yesterday and have blocked time out this weekend to finish up. won't make the milestone (tomorrow) but will finish a first pass before Monday's checkin. 

Some quick observations -- as the color demo is currently set-up this is not an approach to color that designers will find very useful. The branding colors are rarely used in their pure straight hex values -- as this would produce a design that is too overwhelming visually. 

What is more common is that designers take the "pure primary color"  (so for example ucla blue = #3399cc) - and treat it like a variable. The rest of their design elements will use tints or shades of the #3399cc gradient spectrum. 

See the Android color guide as an example (look at their swatches vs. the pure branding colors): 
https://developer.android.com/design/style/color.html -- notice that event though the primary color for blue is #33B5E5 -- there are actually 16 different blues (shades/tints) that have different hex values.

I'm taking a crack at another approach. We should consider SASS vars and mixins for the branded colors and not produce outputted classes that use the pure ".primary/.secondary/.tertiary/.neutral" colors -- if we use a literal single class approach -- this will lead to designs that will have both negative impacts to usability as well as certainly violate many branding guidelines. 

One I can think of immediately -- most brand guidelines say something like this: "use tertiary colors sparingly as design accents" -- if we create a class .tertiary in the pure color that any end-user will apply liberally to a site (to tables/buttons/etc.) -- this will be in direct conflict with the intent of the brand system.

Also we'll want a set of SASS Vars since in most designs the neutral pallet is actually very large (including shadows, type treatments, borders, and UI elements) I end up using about 6-12 shades of greys per design deck -- so instead of .neutral what I need is a set of Vars $neutral-0, $neutral-1, $neutral-2, $neutral-3 ... etc.

See this example Neutral Pallet that is closer to a working pallet for a complex UI system:
![Neutral-Pallet](https://f.cloud.github.com/assets/1393130/44138/c3b28f12-56ad-11e2-8cbd-073c44819709.png)

Bootstrap actually has a very decent neutral pallet that they use for their UI and type treatment -- there's no need to re-invent the wheel -- so to save time for the first round I'm simply going to scrape their color settings and bring them over as vars that can be identified and re-mixed with our new colors in a more harmonious manner. Ideally, since many of the UC Brand guides ask for "warm neutrals" we'd extend Bootrap's base set of greys to include some warm variants.

Hopefully these suggestions and ideas will make more sense once I have a working demo for Monday.

**Comment by alicetseng** [comment]
This is finished! only issue is there is something hosed with my local instance and Github won't allow me to commit the files since its complaining about a conflict with my jQuery package ... might be related to some directories being out of sync ... anyways -- if I can't figure it out I'll just back up the files and rebuild.

**Comment by ebollens** [comment]
I have moved the UCLA colors to a UCLA extension.

To enable the extension, build with the following set in `Rakefile-config.rb`:

``` rb
WebBlocks.config[:src][:extensions] = ['ucla']
```

I'm going to now go in and try to mirror the sort of shadow/accent approach used for the UCLA extension back into the main set of colors. Will likely tweak on a few of these colors as well since right now, `.important`, `.error` and `.danger` all have the same hue set. I'll probably leave `.error` and `.danger` the same in the default set, since they have roughly the same connotation (just at different times when interacting with them), while I will tweak `.important` like done in the UCLA extension.

**Comment by ebollens** [comment]
The commit 97f8501 modified the implementation of the core adapters branding color `_variables.scss` file so that you can hook in at various points in order to define a color scheme, at it will generate the rest. When coupled with the commit 4e8ab37, that modified the load order of variables, what we end up with is the ability to do something like this within an extension:

``` css
$ucla-primary: #3399cc;
$ucla-secondary-gold: #ffb300;
$ucla-tertiary-neon-purple: #8237ff;

$color-branding-primary: $ucla-primary !default;
$color-branding-secondary: $ucla-secondary-gold !default;
$color-branding-tertiary: $ucla-tertiary-neon-purple !default;
```

Unfortunately, the mixin `contrast-color` isn't perfect. When you sit on the threshold for contrast, it doesn't always pick the right flavor of dark or light. As such, I found it necessary in this case to do some minor tweaks:

``` css
$ucla-primary: #3399cc;
$ucla-secondary-gold: #ffb300;
$ucla-tertiary-neon-purple: #8237ff;

$color-branding-primary: $ucla-primary !default;
$color-branding-secondary: $ucla-secondary-gold !default;
$color-branding-secondary-contrast-threshold: 0% !default;
$color-branding-tertiary: $ucla-tertiary-neon-purple !default;
$color-branding-tertiary-contrast-threshold: 100% !default;
```

This forces secondary to use the dark text and tertiary to use the light text. Not perfect, but alright.

A few minor issues that came up:
- Thresholds should be different for light and regular, so we should introduce a `$color-branding-tertiary-contrast-threshold-light` one so that we don't override both light and regular by doing what we did above.
- If might be nice to just override the threshold calculation instead of use 0% and 100% to force override.
- The best way to do color selection between dark or light text would be to do something like an accessibility computation to determine which has a greater contrast ratio (/CC @chris4ucla).

Will make a pass at resolving these, and then I will go ahead and implement for mood as well.
