### ISSUE TITLE
Adaptive Images Integration

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#185]
NOTE: The goal of this ticket has been updated per https://github.com/ucla/WebBlocks/issues/185#issuecomment-24555986

~

While max-width prevents the presentation of images from looking bad on small screens, it doesn't solve the resolution issue. Instead, this needs to be accomplished through some form of compression. The [Mobile Web Framework](http://mwf.ucla.edu) includes an image compressor, but it's currently non-optimal (caching and general efficiency) and discussions are underway on how to improve it, either selecting an existing compression tool or writing a new one.

Two options should be given to someone running this framework:
1. Compress at a certain set of fixed sizes (keeps the cache small and processing low)
2. Compress to the ideal size based on telemetry (larger cache and more processing)

A few tools exist that tackle this problem:
- Adaptive-Images http://adaptive-images.com/ (looks smooth, but challenge with .htaccess since this may run on diff server)
- Mobile Web Framework http://mwf.ucla.edu (would need to rewrite the compression script)
- Responsive Images https://github.com/filamentgroup/Responsive-Images (too clunky with server-side logic)
- Apache Mobile Filter http://apachemobilefilter.org/ (inelegant as requires device repository, but no client-side code)

The interface for end users to implement compression should also be as simple as possible. If they lay in regular images, maybe Javascript transmutes it. However, this has performance issues. Another option would be to provide a class that they assign to images that they want to make responsive - this allows a library to more quickly make the transformations where needed and not waste time where not needed (see the next section on "Image Substitution" as well).

**Comment by loganfranken** [comment]
Hey @ebollens, this is great stuff (nice work!). Where's the "Image Substitution" section that's referenced?

**Comment by ebollens** [comment]
Looks like I missed that in the creation of these tickets.

**Comment by ebollens** [comment]
This has been moved back to milestone 0.1.07.

**Comment by jrosczyk** [comment]
After using both the Adaptive-Images and Responsive Images techniques mentioned above, I am leaning toward the idea of letting the mobile carriers handle compression.
http://boagworld.com/dev/how-should-we-handle-responsive-images/

**Comment by ebollens** [comment]
This is some interesting stuff. Unfortunately, it doesn't look like it's generically offered, so it may not be enough. But what I'm thinking is that we can (a) run an optimizer on the images in the build `img` directory and (b) provide some compression that people can use optionally. There's no harm in providing these extra features, I don't think. What were your results like with Adaptive-Images and Responsive Images?

**Comment by jrosczyk** [comment]
I liked how Adaptive-Images doesn't require any html changes, it finds the images and makes the changes server-side. Unfortunately, it places a cookie and caches the images. I was able to modify the code to get around needing a cookie, but the image caching is something I'd like to avoid (although resizing server-side on the fly slows the performance down too much). This could be a decent technique if we were using WordPress or a dynamic web app as our CMS.

Responsive Images runs the quickest, because it isn't resizing anything just detecting the monitor size and assigning the correlating file, but this would mean all the html image tags would need to be rewritten and smaller image sizes created. This might be the technique I'd use if I was hand-coding a new site from scratch. (Side-note, this would be easy to bundle with WebBlocks. It could even be rewritten to check the file-folder for a larger image without needing the extra filenames in the img src… but that'd still require the site managers to add multiple file sizes for each image.)

To get either one of the above solutions working within our (UCSC) existing websites (100+) inside of our CMS (Cascade Server) would be a lot of work for a solution that wouldn't meet our all performance needs. Recently, I read that 3g and 4g cellular networks are working to solve this issue and have started to compress images. So, maybe (unsure at the moment) the best move for our campus is to not rush into trying to hack this concern and instead live with it a bit before we make a move. (Though if we were using a dynamic cms it might be a different story.)

In regards to image compression… there are many roads to take and all of them seem imperfect. Both dynamic server-side and client-side seem too slow for performance improvement. If this is true, then perhaps having multiple image sizes (cached or otherwise) is the ugh way to go :/

**Comment by ebollens** [comment]
WebBlocks is client-side compiled code; however, given the assenting voices, I hold that we should provide an extension that provides the JS integration code.

The JS integration code is trivial:

``` html
<script>document.cookie='resolution='+Math.max(screen.width,screen.height)+'; path=/';</script>
```

The rest is then probably to provide information about how to get the rest working - via the docs.

**Comment by ebollens** [comment]
In #450, we added support for HTTP Client Hints. This polyfill does the following:

``` js
document.cookie="CH=dh="+screen.height+",dpr="+(window.devicePixelRatio||1)+",dw="+screen.width+",t"+("ontouchstart"in window||"msMaxTouchPoints"in navigator)+";expires=Fri, 31 Dec 9999 23:59:59 GMT;path=/";
```

It's pushing the same data set as Adaptive Images needs, except that the Client Hints polyfill sets comma-separated key-value pairs, whereas Adaptive Images just sets values. Seems to me that, since HTTP Client Hints is working its way towards being a spec, why not tweak on Adaptive Images to support it?

I've put together my work here:
https://github.com/ebollens/Adaptive-Images

The only thing that changed is that now, if the `resolution` cookie isn't set, it checks for a cookie by the name `CH` or else a server value of `HTTP_CH`. I'll push through some documentation that explains the integration, and I might also drop in the Adaptive Images hook - just in case people would rather use that then the fork I've put together.

/CC @loganfranken @jrosczyk

**Comment by ebollens** [comment]
I've added an `:adaptiveimages` package that writes the `dimension` cookie.

Docs on this are available in my deployment of `ghpages` tracking WebBlocks 1.1 development:
http://ebollens.github.io/WebBlocks/doc/#API/Package/adaptiveimages

On that page, I also mention the Adaptive Images fork that will use HTTP Client Hints. If someone uses the fork of Adaptive Images from https://github.com/ebollens/Adaptive-Images, then they don't need to enable `:adaptiveimages` but rather can just enable `:httpclienthints` and call it a day. I've also submitted a pull request from my fork that adds HTTP Client Hints support (as a fallback to the Adaptive Images cookie it traditionally uses) - if they accept the fork, then we don't need the `:adaptiveimages` plugin at all  :smile:
