### ISSUE TITLE
Test Build Process with Windows 7

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#2]
Build script needs to be updated to support Windows 7.

**Comment by ebollens** [comment]
Tested current version in both OS X 10.7 and Windows 7 and appears to work in both - may be necessary to tweak for support in other versions of Windows and *NIX operating systems later.

**Comment by ebollens** [comment]
Given changes in #8, #11 and #13, this needs to be retested under the Windows environment.

**Comment by ebollens** [comment]
I am pleased to say that this passes with all the changes in #5, #8, #11 and #13.

**Comment by loganfranken** [comment]
I was just getting this set up and it worked like a charm!

However, the Rakefile wouldn't run for two reasons:
1. I hadn't installed Bundler 
2. I had the newest version of Sass installed (`3.1.20` instead of `3.1.19`)

Both of these are the same issue of course: I should have just executed `bundle` from the start. Anyway, since you did such a nice job with the Gemfile and node package, I was thinking we should explicitly mention Bundler as a prerequisite and remove the manual instructions from the README (you mention both as "also" caveats). I would make the edit myself, but I wasn't sure if I missed something obvious as a Ruby/node.js newbie?

**Comment by ebollens** [comment]
Logan, thanks for the confirmation! I'll update the README to recommend using Bundler directly instead of trying to manually walk a user through the process. I'll continue to include the manual instructions as well, but I'll make them the "also" bit instead.

PS. I'm a Ruby and node.js newbie myself too ;)
