### ISSUE TITLE
Billboard Prototype

### ISSUE THREAD

**Issue by alicetseng** [ucla-oarc-web/WebBlocks#21]
Discussions on whether this should be a hero-image or a hero-unit (a la bootstrap) - @modernrockstar , @ebollens , @loganfranken  -- thoughts on this? wiki page is here: https://github.com/ucla/WebBlocks/wiki/Billboard

**Comment by ebollens** [comment]
I agree with @loganfranken that we should provide a unit that supports more than just an image - and as @atsengucla says, we should make each component optional. However, I'm wondering if hero is the right name for it, because when you Google either "hero image" or "hero unit", besides Bootstrap, not much terminology uses it.

I support the idea of using `figure` for it.

**Comment by alicetseng** [comment]
it's kinda a niche industry term. If you google "ux hero image" or "ux billboard image" you'll come across more mentions. I've heard it referred to as either the "hero image" or a "billboard" -- it's mainly used for marketing sites to convey some brand narrative. I'm neutral to the term we use as long as it makes sense that it's for marketing/narrative story-telling.

**Comment by loganfranken** [comment]
Ooh, I like billboard.

**Comment by ebollens** [comment]
Right now, this is still `figure/heroimage` and it's just a straight HTML file right now. Can someone please define prototype, change ex name and provide an example image as well? Thanks!

**Comment by albertwu** [comment]
I like billboard as well. It describes much better the intent of that content type.

**Comment by alicetseng** [comment]
Sure. I can do this -- it looks as if there are 2 votes for billboard so I will propose a draft with that and if there are objections/votes for "hero " please speak up.

**Comment by ebollens** [comment]
I'm +1 on billboard as well.

**Comment by alicetseng** [comment]
OK. So Billboard is clearly agreed on. 

But looks like more thought needs to go into what the element markup should be. I'm striking my own original proposal for the figure entity based on more reading. The figure entity needs to be "not effected" by its position change in the flow of content. Billboard as the Primary element of a marketing landing page does need to have "primary position" in the content flow. 

See notes here: https://github.com/ucla/WebBlocks/wiki/Billboard. I'd appreciate thoughts on this. Leaning towards div wrapper on this one.

**Comment by alicetseng** [comment]
reorganized billboard and cleaned up prototype + wiki to reflect div|figure options.

**Comment by alicetseng** [comment]
Update issue name and issue links for better trail.

**Comment by loganfranken** [comment]
Hopefully it was alright: I was cleaning up some orphan issues and I assigned @atsengucla to this one since you've already been doing the majority of the work on it, Alice.

**Comment by alicetseng** [comment]
@loganfranken and @ebollens - OK back from 2 week vacation and catching up on the development stream; will update the gallery and billboard readme files to incorporate the newly added features sections. thanks/catching up! These should be ready to push to dev soon.

**Comment by alicetseng** [comment]
@ebollens @loganfranken @modernrockstar (anyone else) please give this entity a once over. I've updated the prototype, readme and wiki. If no problems/issues can be found, I'd like to push this to pending dev.

**Comment by loganfranken** [comment]
@atsengucla Looks good! I think the carousel-specific markup could be moved from the prototype since it may become too difficult to have that definition spread across too many prototypes. (Maybe we could just have a placeholder where either a `img` or a `figure.gallery` could be slotted?)

We'll have to deal with the separated player controls at some point, but that could probably be dealt with a little later (and would probably be more of an issue specific to the carousel entity).

Besides moving out the gallery markup (if everyone else agrees), I vote that this is ready to ship off.

**Comment by ebollens** [comment]
@atsengucla @loganfranken conceptually I think it's too verbose in classes. What would you think of:

``` html
<!-- 1 -->
<div|figure class="billboard"> <!--use div if position in flow of content matters, otherwise figure -->
    <!-- 1 : if static image type 1..* if player type -->
    <img src="{Image 1 Thumbnail URL}" alt="{Alt description text}" />

    <!-- 0..1 -->
    <hX>Some Title here</hX>

    <!-- 1 -->
    <p|figcaption>Some Great Marketing Pitch Here</p|figcaption>
    <(a class="button"|button) href="{Image 1 URL}">Some Call-to-Action Link or Button</a|button>
</div>
```

My thought here is:
- The class `tagline` is superfluous because we've strictly defined the entities that are allowed to be the pitch.
- There is no need for a class on a `button` element, as its purpose is clear. No other buttons used in this context.
- The class `title` is superfluous as that's what the `hX` represents.
- We should support any of the header elements, not just `h2`.
- So far, we're using the class `.button` for `a`-based buttons, not `.btn` (which is a Bootstrap thing).

Similar changes would apply to the second version.

However, other than that, looks good in my book.

**Comment by loganfranken** [comment]
I second @ebollens's suggestions.

To be clear, I was proposing we do the following:

``` html
<!-- use div if position in flow of content matters, otherwise figure -->
<!-- 1 -->
<div|figure class="billboard">

    <!-- Billboard image can be replaced with the "gallery" component to add an image carousel -->
    <!-- 1 -->
    <img src="{Image 1 Thumbnail URL}" alt="{Alt description text}" />
```

Not sure if we wanted to develop a particular syntax for slotting Web Blocks components into prototypes?

**Comment by alicetseng** [comment]
@ebollens and @loganfranken - valid points both of you. I'll make the updates this afternoon/evening.

**Comment by alicetseng** [comment]
@loganfranken -- I'm going to rely on you and others (devs) for that convention; that's getting more into dev than I can speak to -- let me know what you think and I can update the syntax once a convention has been settled - a syntax will be needed -- I see that pattern cropping up with the more complex entities like header/gallery/billboard.

Second is just a clarification: so totally get your suggestion to slot billboard with gallery -- makes sense. The gallery component right now supports 2 forms that semantically are the same (both lists of images) but the visual rendering is very different - the static form is a grid of thumbnails and the interactive form a player that looks more like a billboard in form (a large image well) that displays one image at a time ... is this going to be a problem when we try to implement this? Do we need to clarify the two types of gallery and only slot the second type into the billboard? thoughts?

**Comment by ebollens** [comment]
In terms of signifying an entity within an entity, I was using this style:

``` html
    <!-- 0..1 -->
    <nav class="bar">
        <!-- see entity/nav/bar -->
    </nav>
```

Maybe "see" isn't the right word but something like this:

``` html
    <!-- 0..1 -->
    <nav class="bar">
        <!-- [[Entity/Nav/Bar]] -->
    </nav>
```

If it needed to have multiple classes, then you could do something like:

``` html
    <!-- 0..1 -->
    <nav class="bar otherClass">
        <!-- [[Entity/Nav/Bar]] -->
    </nav>
```

This would allow you to clarify that only one type of gallery can be slotted - kind of. The problem is that it looks to me that contextually the only way to know what type of gallery is, you can't just look at the gallery figure itself. Maybe there's a way to specify which of the different types like this:

``` html
    <!-- 0..1 -->
    <nav class="bar">
        <!-- [[Entity/Nav/Bar with such and such]] -->
    </nav>
```

**Comment by loganfranken** [comment]
When specifying an entity within an entity, I was wondering if maybe we shouldn't even include the markup at all since the basic markup could possibly differ (a blockquote's parent element could be either  a `blockquote` or a `figure`, for example).

So, instead of:

``` html
<div class="example-component">

    <!-- 0..1 -->
    <blockquote>
        <!-- [[Entity/Nav/Blockquote]] -->
    </blockquote>

</div>
```

We would have:

``` html
<div class="example-component">

    <!-- 0..1 -->
    <!-- [[Entity/Nav/Blockquote]] -->

</div>
```

**Comment by ebollens** [comment]
Makes sense to me

On Aug 25, 2012, at 11:44 PM, "Logan Franken" <notifications@github.com<mailto:notifications@github.com>> wrote:

When specifying an entity within an entity, I was wondering if maybe we shouldn't even include the markup at all since the basic markup could possibly differ (a blockquote's parent element could be either a blockquote or a figure, for example).

So, instead of:

<div class="example-component">

    
    <blockquote>
        
    </blockquote>

</div>


We would have:

<div class="example-component">

    
    

</div>

**Comment by loganfranken** [comment]
I updated the wiki with that syntax:
https://github.com/ucla/WebBlocks/wiki/Creating-an-Entity-Prototype

**Comment by alicetseng** [comment]
This design issue is closed; ready for implementation.

**Comment by loganfranken** [comment]
Created implementation issue: #85
