### ISSUE TITLE
DIV / UL Row, not inline

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#227]
I have a row, with a 6-6 panel split, one is a UL, one is a DIV.  Taken from example provided earlier this is the basic markup.

Right now, both elements are stacked, as if there is a clear being applied to the div.

I am unsure if this is the wrong syntax, or if there's a complication with UL / DIV on a row.  I have no floats nor clears applied to any elements within the footer.

```
<footer class="dentFooter row">
  <ul class="dentFooterLinks panel-6">
    <li></li>
    <li></li>
    <li></li>
    <li></li>    
  </ul>
  <div class="dentFooterSprites panel-6">
    <div id="dentFooterSpriteEmail"> <a href="#" title="Contact us via email">TEST</a> </div>
  </div>
</footer>
```

**Comment by lnicks** [comment]
Strangely enough, in reverse it appears to be working fine.  That is, if the div comes first, instead of the UL, it works.

http://dentistrydev.oit.ucla.edu 

You can see an example here: The header is a div/ul panel-6 split.  The footer is a ul/Div panel-6 split.

/cc @ebollens @chris4ucla

**Comment by lnicks** [comment]
my `[app/dentistry]` branch is up to date with my most current settings if you need them.

**Comment by ebollens** [comment]
The problem accrues here because the `ul` element, under most browser default sheets, includes a `margin-left` attribute (you can see this with the Web Inspector, for instance). While we could put in a hack that thwarts this, it's going against browser conventions. As such, my recommendation is this:

``` html
<footer class="dentFooter row">
  <div class="panel-6">
    <ul class="dentFooterLinks panel-6">
      <li></li>
      <li></li>
      <li></li>
      <li></li>    
    </ul>
  </div>
  <div class="dentFooterSprites panel-6">
    <div id="dentFooterSpriteEmail"> <a href="#" title="Contact us via email">TEST</a> </div>
  </div>
</footer>
```

I will add mention to this in the documentation that some elements, such as `ul` are not suited to be used as a `panel` directly because they include `[left|right]-margin` attributes.
