### ISSUE TITLE
Handling borders and the box model

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#280]
I'm trying to add a border to an element that spans the entire width of the page. I am unsure how this is handled in webblocks.

Right now, the I've got the width set to 960px in variables.css, but the box ends up being 962px, thus the right border isn't showing.

This may be way easier than I am making it, but I don't know what the best method for handling this is.  Didn't see anything in the documentation directly related to borders on a box.

/cc @chris4ucla

**Comment by loganfranken** [comment]
Not sure if this fits your needs, but on a project that I'm working on at the moment I solved this by putting the element with borders into a wrapping `div` with one of Web Block's structural elements. So, instead of:

`<div class="component panel-4"></div>`

(Where `component` has borders) I switch it to:

```
<div class="panel-4">
   <div class="component"></div>
</div>
```

The extra `div` is a little undesirable but I feel like it's one of those "framework compromises" we have to make since Web Blocks is targeting such a broad audience.

**Comment by lnicks** [comment]
This is a good idea.  I keep forgetting we can wrap things.

I'm using it in a list right now, so the `UL` itself is the max width object, but since the `UL` is in a `LI` from the previous list , I might be able to put a `div` around it.  

Will give it a shot, thank you!

**Comment by ebollens** [comment]
The alternative is to use the `box-sizing:border-box`. More details are here:
https://developer.mozilla.org/en-US/docs/CSS/box-sizing

However, we've chosen not to use this because there's no transparent hack that can solve the issue of support for earlier versions of IE; while IE7 isn't completely supported, relying on this would completely break the IE7 gridding, so I elected to ignore it. It may make sense for us to come back at this a bit later depending on feedback from others.
