### ISSUE TITLE
rake clean task removes entire target directory instead of individual files

### ISSUE THREAD

**Issue by alroman** [ucla-oarc-web/WebBlocks#299]
There could be non WebBlocks created files that need to survive this task.  It would be better if this task only deleted WebBlocks created files.

**Comment by loganfranken** [comment]
:+1:

Also: if you specify custom build directories, does it clear out those directories as well? I could have sworn it did in one of my projects, but I haven't had a chance to go back and verify.

**Comment by alroman** [comment]
If I specify a custom build directory for images, it wipes out all images that previously existed in the directory.  It looks like custom directories for css & js don't have this behavior.

**Comment by ebollens** [comment]
Currently, the `rake clean` task operates by deleting the whole WebBlocks directory:

``` ruby
      def clean

        log.task "WebBlocks", "Removing build directory" do
          FileUtils.rm_rf build_dir
        end

      end
```

The problem is that, if you have placed something in `/img` or `/js/script`, but then removed in subsequently, there's no good way to chase it down. Consequently, you either end up deleting too much or too little. It's probably better to obliterate too little rather than too much, though, so I'm going to make a change that only obliterates the `blocks-[ie].[css|js]` files.

To tell you the truth, I'm not even completely convinced there's a real purpose to this task.
