### ISSUE TITLE
Entity/Nav/Main

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#30]
Development task for the `entity/nav/bar` element.

**Comment by ebollens** [comment]
@atsengucla @ccheung as you two volunteered to take a pass at masthead, I've also generated the skeleton for `Entity/Nav/Main` in `src/sass/adapter/bootstrap/entity/nav/_main.scss`.

**Comment by ccheung** [comment]
@loganfranken - as discussed in the meeting on Monday, since you'll be focusing on Entity/Nav I'm going to reassign this task for you.  Thanks!

**Comment by loganfranken** [comment]
Before digging into implementation, I wanted to get a better understanding of the requirements for this entity. I've put my current research in the wiki:
https://github.com/ucla/WebBlocks/wiki/Entity-Nav-Main

@ebollens @atsengucla @ccheung Is this what you were thinking for this entity?

Also, it looks like there's going to be a lot of opportunity for borrowing from currently existing entities, to the point that this entity might instead get split into extensions for currently existing entities (adding mega menu support for nav bar, for example). But, we'll see.

**Comment by loganfranken** [comment]
Moving this to 0.1.05. Maybe we could discuss the requirements tomorrow?

**Comment by loganfranken** [comment]
Moving to next milestone

**Comment by ebollens** [comment]
@atsengucla mentioned at the last meeting that she could work up style sheets and template for this to make implementation simpler. Assigning to @atsengucla. Please assign back once these are committed. 

Goal should be to design what the main navigation looks like at each of the different viewports where it changes (don't have to worry about media queries or that stuff but simply provide different files).

**Comment by alicetseng** [comment]
started working on this; reviewing patterns and bootstrap existing library. will have some time Tuesday evening to get some html/css mockups going.

**Comment by ebollens** [comment]
@atsengucla sounds good. @lnicks needs this soon for a project he's working on with Drupal, so I'll turn around and implement as soon as you pass the CSS of my way.

**Comment by alicetseng** [comment]
Wow. This one is hairy. Will keep working on this. I have some time tomorrow night after work. It's gonna take a few more passes, tho. I could use some help clarifying the relationships ... 

Here are my questions ( @loganfranken and @ebollens ) - trying to understand how nav.bar fits with nav.main  - as well as 2 JS related classes --  .dropdown and .list (for the new responsive submenu) that were introduced by WebBlocks when entity/nav/bar was created. Is this .dropdown being inherited from bootstrap ? and is it being used in the same way?   

I'm trying to wrap my head around all the dependencies and come up with some coherent pattern -- Is the following sorta on the right track?

From what I can understand -- nav.main is defined as not nav.list, not nav.bar, not a secondary type nav element that is wrapped inside .masthead. 

By default its a nav with its 1st level children items set as a horizontal floated list with possible/optional .dividers such as: nav.main.colon, nav.main.pipe, nav.main.carat ( I saw there was already a .divider class -- but I'm wondering it it'll be more elegant if I use :after to generate the :, |, > -- instead of using the span method -- since these dividers are not meaningful content in the case of main navigation as they are in breadcrumbs that denote a hierarchy).

It seems like there are also some visual styles for the 1st level children items such as: nav.main > ul.pills , nav.main > ul.tabs, nav.main> ul.bar  (?)  This last one is confusing me - since we already have a nav.bar but what about a situation when the main nav has a bar style for wrapping its first-level list items ?

If we follow the above logic (that nav.main is fundamentally different from nav.bar), perhaps nav.main implies that it contains a deeper hierarchy with sub-children -- so we can have nav.main > ul.sub -- with .sub meaning "sub-children" (or from bootstraps naming convention dropdown-submenu ). 

And thus, we can have something like the following: nav.main > ul.sub (the default is a single list type drop-down menu like the one that comes already with bootstrap) and nav.main >ul.sub.mega (when the situation applies to a multi-column submenu that we see in mega menus).

I'm trying to avoid .dropdown and something like .menu -- since the first is already taken and it's actually describing a behavior and not describing the form of the sub-lists -- both the simple single list type and the multi-column (multi-list type) are technically dropdowns. And since .dropdown used so heavily across all types in bootstrap, I'd like to avoid that one for this case -- to avoid any accidental clashes. 

So these would be the classes that are the possible set I'd be working with for entity nav/main :
nav.main.colon | nav.main.pipe | nav.main.caret 
nav.main > ul.pills | nav.main > ul.tabs | nav.main > ul.bar 
nav.main > ul.sub | nav.main > ul.sub.mega

In addition I'd bring over the ones that look like they are already being used -- such as: 
.active, .dropdown (for JS behavior), .close 

I'm trying to be mindful to break as few of the dependencies as possible while still working with our semantic structure - let me know if the above sounds sane. 

I think this is the part I'm having the hardest time wrapping my head around. Once the relationships are clarified -- I can easily bring the styles over and rewrite where our re-structuring breaks the dependencies for styles.

**Comment by ebollens** [comment]
@atsengucla I'm going to break this down topic by topic...

> trying to understand how nav.bar fits with nav.main

I think the concept of `nav.main` is more that of a mega-menu than _necessarily_ the main menu, although the two often serve the same purpose. As such, using `nav.main` might actually be the wrong route and we should be using something like `nav.mega`.

Eventually, I intend to add two-tier support for `nav.bar`, but that's different than this entity.

> as well as 2 JS related classes -- .dropdown and .list (for the new responsive submenu) that were introduced by WebBlocks when entity/nav/bar was created

In the final implementation of Entity/Nav/Bar, I do not believe we ended up with these two JS-related classes.

> Is this .dropdown being inherited from bootstrap ? and is it being used in the same way?

No, the dropdown isn't being inherited from Bootstrap, and in fact we need to polish it with some reasonable-looking CSS definitions. Right now, it's functional but not yet pretty. You can take a look at it in the demo folder.

> From what I can understand -- nav.main is defined as not nav.list, not nav.bar, not a secondary type nav element that is wrapped inside .masthead.

On the whole, yes, this entity should be able to stand _on its own_ without being entrenched in something like a masthead. However, masthead might regard it in a particular way and make some additional style decisions as pertaining to it - but that's not the concern of this implementation ticket. This is the functional prototype to design against in terms of semantics:
https://github.com/ucla/WebBlocks/blob/master/template/entity/nav/main/prototype.html

> nav.main.colon, nav.main.pipe, nav.main.carat ( I saw there was already a .divider class -- but I'm wondering it it'll be more elegant if I use :after to generate the :, |, > -- instead of using the span method -- since these dividers are not meaningful content in the case of main navigation as they are in breadcrumbs that denote a hierarchy).

I prefer to use the `:after` selector and make this invisible to the user. However, possibly you can allow one to be explicitly or implicitly defined. If explicit, I like the `.divider` pattern better, where the character is actually specified, since they're already being explicit to a point. However, don't worry much about this in the styling. I just need the overall conceptualization.

> It seems like there are also some visual styles for the 1st level children items such as: nav.main > ul.pills , nav.main > ul.tabs, nav.main> ul.bar (?) This last one is confusing me - since we already have a nav.bar but what about a situation when the main nav has a bar style for wrapping its first-level list items ?

It wouldn't be `nav.main > ul.bar`. Instead, I figure it would be `nav.main.bar`. However, I'm inclined to say, don't worry about this for now. Instead, focus on this as a unique entity distinct from the others.

> So these would be the classes that are the possible set I'd be working with for entity nav/main :
> nav.main.colon | nav.main.pipe | nav.main.caret 
> nav.main > ul.pills | nav.main > ul.tabs | nav.main > ul.bar 
> nav.main > ul.sub | nav.main > ul.sub.mega

No, actually you're just working with this prototype:
https://github.com/ucla/WebBlocks/blob/master/template/entity/nav/main/prototype.html

We're not _requiring_ the use of Bootstrap, so thinking about this in terms of Bootstrap classes creates problems.

**Comment by alicetseng** [comment]
@ebollens - ok thanks this helps clarify things a little better.

I think the concept of nav.main is more that of a mega-menu than necessarily the main menu, although the two often serve the same purpose. As such, using nav.main might actually be the wrong route and we should be using something like nav.mega.
- I think nav.mega is a clearer name to its purpose than nav.main - saying it this way helps me better visualize its relationship to the others and helps focus the scope of this entity.

**Comment by ebollens** [comment]
Okay, then unless @loganfranken objects, I propose we change Entity/Nav/Main to Entity/Nav/Mega.

**Comment by lnicks** [comment]
@atsengucla's suggestion makes sense to me. The .main portion conveys to me a location on the page, in relation to the content which may not always be the case.  ex. We use the mega menu concept in footers as well.

**Comment by alicetseng** [comment]
@ebollens and @lnicks - sorry for the delay - I've been swamped with other work - anyways since you're waiting for this I'm giving you a first pass to get started and if I'm on the right track after the basic SASS mixins have been created I can come back this weekend to help set color vars and additional styling extensions. I have some time Saturday.

I'm still having issues with the git GUI - and don't have time to mess with it right now so what I'm going to do is just ping it as a zip named "WebBlocksDemo" and post it to you via the group email list. -- since its just a css prototype - figure this better than me accidentally pushing a conflict through since the github GUI commands are still a little abstract to me.

**Comment by alicetseng** [comment]
@ebollens and @lnicks :

Here's the css/html prototype for entity/nav/mega. Hopefully I'm on the right track — since our last convo it seemed like there was no need to follow Bootstrap on this so I just extended what seemed to make sense and rewrote styles to work visually with what we already have.

Colors are set to boostrap defaults but meant to accept WebBlocks color Vars when this gets implemented in SASS. The mobile sub-menu should extend the patterns already established (see notes in html doc).

Attached as zip — I'm wrapped up in another project today – but have some time Sat to give this more time if help is needed.

-a

**Comment by loganfranken** [comment]
I'm responding way late here, but I support the switch to `Entity/Nav/Mega`.

Also, on the topic of the divider: I personally prefer using `:after`. I opted not to use it (in entities like the breadcrumb) because the explicit `span` lets Users define the divider glyph easier. I wonder if we could support both options somehow?

**Comment by ebollens** [comment]
This has been moved back to milestone 0.1.07.

I agree that `:after` is preferable in many regards.

**Comment by ebollens** [comment]
This is new semantics, so I'm moving it to v0.2.00 milestone, as there hasn't been any more traction on it.

**Comment by ebollens** [comment]
The `nav.bar` discussed here was already implemented, and the main use case we've been trying to capture here is a mega-menu. Consequently, closing this as superceded by #449
