### ISSUE TITLE
Entity/Nav/Bar

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#31]
Development task for the `entity/nav/bar` element.

**Comment by ebollens** [comment]
In the commits I've pushed through so far, I've started _tinkering_ with the navbar.

At this point in time, the adapter for Bootstrap handles the layout properly for `header|aside + ul` and `ul + header|aside` with floats using `overflow:auto` to ensure that `nav.bar` _contains_ the entirety of the floated elements, such as allowing for a `background-color` to be set on the `nav.bar` rather than the floated child nodes. I've also added the `nav.bar.bottom` and `nav.bar.top` to go fixed position on the screen.

An example of the markup here:

``` html
<nav class="bar">
    <header>Title</header>
    <ul>
        <li><a href="#">Item 1</a></li>
        <li><a href="#">Item 2</a></li>
        <li><a href="#">Item 3</a></li>
        <li><a href="#">Item 4</a></li>
        <li><a href="#">Item 5</a></li>
        <li><a href="#">Item 6</a></li>
        <li><a href="#">Item 7</a></li>
        <li><a href="#">Item 8</a></li>
        <li><a href="#">Item 9</a></li>
        <li><a href="#">Item 10</a></li>
        <li><a href="#">Item 11</a></li>
        <li><a href="#">Item 12</a></li>
    </ul>
</nav>
```

An alternative might be something like:

``` html
<nav class="bar">
    <ul>
        <li><a href="#">Item 1</a></li>
        <li><a href="#">Item 2</a></li>
        <li><a href="#">Item 3</a></li>
        <li><a href="#">Item 4</a></li>
        <li><a href="#">Item 5</a></li>
        <li><a href="#">Item 6</a></li>
        <li><a href="#">Item 7</a></li>
        <li><a href="#">Item 8</a></li>
        <li><a href="#">Item 9</a></li>
        <li><a href="#">Item 10</a></li>
        <li><a href="#">Item 11</a></li>
        <li><a href="#">Item 12</a></li>
    </ul>
    <aside>Title</aside>
</nav>
```

One thing that dawns on me as I'm looking at the Gateway, however, is that in their case they appear to have both a header and an aside. However, my personal feeling is that this is a special case, but maybe more discussion is needed in #9 on this topic. I'll bring it up there.

To explain a bit about my process, at first I had tried to use a bunch of `@extend` calls with Bootstrap classes. Unfortunately, the structure of `.navbar` and it's children isn't very friendly, and it's made unmanageable for extending by the fact that extend does not support inheritance of _nested selectors_. On the whole, the takaway here is that some inheritances like `.btn` will be easy, but others like `.navbar` are all but impossible, leaving us to have to fend for ourselves.

Next up with this will be tackling multi-line overflow of the menu items. To do this, I'm considering using a Javascript method as follows:

``` js
$(window).resize(function(){
    $('nav.bar').each(function(){

        var overflow = false;

        if($(this).css('position') == 'static')
            $(this).css('position', 'relative');

        $(this).find('> ul li').each(function(){
            if($(this).position().top > 1)
                overflow = true;
        });

        if(overflow){
            // create dropdown icon that can lead to a menu that extends down from the bar
        }else{
            // hide dropdown icon and restore menu to its original form
        }
    });
});
```

To do this, however, I first need to add a bit more architecture to the build tool, namely support for additional Javascript libraries. This task is covered in issue #22.

**Comment by ebollens** [comment]
Agreed by Logan that he will handle this so reassigning.

**Comment by alicetseng** [comment]
Hey @loganfranken,

Curious where you're at with nav bar ... if you're at a point to lend some advice?

Celia and I were poking around today trying to figure out the structure and we came across a few issues/notes and wanted to see if you encountered the same/ had any work-arounds. 

What is the verdict on handeling Twitter's dependencies on wrappers? 

It seems like Twitter's nav bar relies on an outer wrapper .navbar and and inner .navbar-inner to contain the gradient fill.

At first look this seems like div bloat but when we read further we found out that this is actually a known work-around to deal with IE9's inability to render CSS3 gradients and overflow. See write-up on this technique: http://timmywillison.com/

When we dug in the bootstrap library .scss files we found this comment in Line 17 of _navbar.scss for .navbar-inner: 

// Gradient is applied to it's own element because overflow visible is not honored by IE when filter is present 

A search on the web produced this github issue : https://github.com/twitter/bootstrap/issues/97

In addition, it looks like their current technique for collapsed menus is via a class that targets the child items with some JS -- so while the wrapper .navbar is an extra shim for the IE9 filter/gradient issue -- it also serves as the hook for their responsive .nav-collapse. 

Thoughts on this? Do we have any alternate work-arounds for overflow/IE9 ? or for .nav-collapse ?

We were able to mock-up a pretty clean implementation of the Masthead that was very close to the original UCLA header layout, responsive with collapsed menu, and pretty respectful of our html structure prototype -- only issue were these navbar wrappers.

When we tried to take apart the outer/inner all the children dependencies of .navbar broke -- seems like the search, responsive toggle, and a whole list of other selectors are depending on a .navbar parent in their library in order to render. As it was about 15 selectors (pretty healthy chunk) it kinda worried us about how'd we'd maintain such heavy customizations. 

Any ideas from you or @ebollens would be great.

-alice

**Comment by alicetseng** [comment]
Notes: From meeting today 10/01 it was decided that the issue (above-- IE gradient/ filter + float bug) would be addressed with javascript to write the wrapper div class specifically for IE+ rather than introduce a wrapper div (navbar-inner). It was also agreed upon to open a separate implementation ticket to track this.

**Comment by alicetseng** [comment]
@ebollens and @loganfranken - please see uploaded navbarCSS in template/entity/nav/bar/navbarCSS. There's quite a bunch of children and dependencies that will be affected by our change of names and nesting logic. So much that I needed to add a spread sheet to manage it. So -- we might want to think this one through a bit. It's doable as the demo shows  -- but we'll need to find a way to manage all the cases when inheritance structure prevents us from using an @extend. The problem is once you do .class>ul>li>a -- for the base -- due to specificity you'll need to replicate on all subsequent overwrites. And this means forgoing a nice clean @extend. I included the spreadsheet with the original SASS vars/@mixins/@extends -- maybe you can think of something more elegant using SASS logic ?

**Comment by alicetseng** [comment]
to access download the whole navbarCSS file and open html page in browser (works in Chrome & FF) - will not in IE since we broke the navbar-inner wrapper for their IE hack.

**Comment by ebollens** [comment]
@atsengucla completely understandable that we skip `@extend` on this one - I was pretty much already expecting this.

@loganfranken want me to take this one since I already volunteered to write the responsive switcher?

@atsengucla as I mentioned in the other issue #127, please let me know what I need to go to polyfill for IE.

**Comment by alicetseng** [comment]
@ebollens and @loganfranken - yep. I can work on the IE stylesheet - but before we proceed -- can we clarify the naming conventions so I can check that I'm on the right track? 

I added an explicit .-nav and also an explicit .-linklist which both I feel are beneficial to supporting the full use-cases for navigation and (list of links) use-cases (see my notes in demo code). Are these good by your reading?

Also, what will be our approach for handeling situations where we have cross-entity nesting? On the chart I've identified other entities that the navbar will be a parent of. 

From what I _think_ I'm understanding from the SASS documentation -- I'm wondering if these children should be handeled as @mixins that @extend their base classes? I know these bleed into other entities -- some that have been implemented already and some that are in current dev -- so we might just say its too disruptive and leave everything hard-coded in the parent context this round. 

Let me explain further (and let me know if I'm understanding the problem -- or not).

Children of NavBar that are cross-scope with other entity classes:
Buttons, Button Groups, Button Bar, Icons, Form Elements, Container, Linklist (what Bootstrap calls .nav), Dropdowns

Could these be defined as SASS @mixins? So that we can reference them in NavBar w/o needed to hard code them. And thus, when the source of the child is updated, the Navbar reference is as well? 

3 things that seem promising about the use of these children elements as @mixins:
1. That @mixins can accept logical operators
2. Parents can be targeted by @mixin nesting
3. @mixins can accept arguments in their declarations

So we can say the following:
the Button base characteristic is this set of css declarations that all Buttons share across.
If its parent is the navBar do this X extra set of CSS with these args (A,B).
If its parent is the masthead do this X extra set of CSS with these args (A,C).
If its parent is the main-content do this X extra set of CSS with these args (A,D).

**Comment by alicetseng** [comment]
quick checkin. @ebollens and @loganfranken -- can you let me know if this is on the right track? I want to move on to finish off masthead's css files and scratch that off the to-do for this milestone 10/27. Just want to confirm that the this is a sane approach. The dependencies are cross-referenced from .-masthead and .-nav .-bar. Also, is .-nav and .-linklist a go? As .-linklist will be a child of other nav components (such as .-main, .-list, etc.) -- want to make sure you're cool with the logic before charging ahead. Finally, how shall we deal with cross-scope children of .-nav .-bar ? Like the issue of .-icon etc. Should that actually be an extension off of .-icon rather than .-nav .-bar ?

**Comment by ebollens** [comment]
@atsengucla you are definitely one the right track with this characterization:

> So we can say the following:
> the Button base characteristic is this set of css declarations that all Buttons share across.
> If its parent is the navBar do this X extra set of CSS with these args (A,B).
> If its parent is the masthead do this X extra set of CSS with these args (A,C).
> If its parent is the main-content do this X extra set of CSS with these args (A,D).

I've taken a look at the bits you've implemented at it looks solid. I've been horribly bogged down with other work, but I'll shift over to this tomorrow and get it transferred into SASS and I'll let you know if I run into any problems along the way. I should have more concrete feedback then.

After I do the transfer into SASS, I'll let you know why I made the choices I made. Most likely, it's going to come down to a question of three approaches for moving attributes around:
1. You have a class that's a modifier on an existing class or that is a modifier of an internal element based on a class. 
2. You use an `@extend` to get its selector attached in all places of another
3. You use `@include` to invoke a mixin, which pulls the same definitions in as from wherever else its used

When I implement this into SASS, I'll let you know the scheme that worked best and where I ran into any problems.

**Comment by alicetseng** [comment]
cool. no worries -- can completely understand being bogged down. Just wanted to make sure before I did the same logic to masthead to get a sanity check. alright-- I'll move on and do the same with the masthead -- implement css applying the same logic and leave you a spreadsheet with SASS bits if I see anything re-usable. Then I'll tackle the color ticket.

**Comment by ebollens** [comment]
@atsengucla so far what you've worked up with the CSS file seems to be really helpful! I've got the basic `nav.bar` class implemented, along with `nav.bar.top`, `nav.bar.bottom` and a special float right support extension for the title. Everything seems to be working well, and as an added bonus, you can actually style the `nav.bar` with ANY of the mood or branding colors, which I think is a pretty big win over what Bootstrap supports. Next up is the toggle functionality, and then the IE fix.

**Comment by ebollens** [comment]
Oh, also, I went ahead and added a couple lines of Javascript that solves the body padding problem when using `nav.bar.top` or `nav.bar.bottom` so that you don't have to set special styles on your body to get the top or bottom of your content to not placed under the fixed bars.

**Comment by ebollens** [comment]
Wahoooo! Commit is now in that handles the dropdown.

Took way longer than I expected because Javascript was hitting a race condition because it runs in a separate thread from CSS reflow, but everything should be working correctly now. As it stands at the moment, I use some Bootstrap variables, but there is very little in there that of Bootstrap that is actually extended. This is because (1) you cannot extend child selectors and (2) our implementation is pretty different.

@atsengucla one thing for you to do would be to restyle the auto-imposed dropdown trigger (if you don't place your own) to look better. One thing to keep in mind is that we should try to use the inherited font color however we style this, because I've got the menu supporting all the colors in our palette and it's not really possible for us to figure out the color that the button background and image should be except by inherit (well, not without increasing the CSS size too much).

I'll try to figure out what's going on with the IE stuff next.

**Comment by ebollens** [comment]
Okay, from what I understand, here are two problems:

> IE9...does not yet support css3 gradients. It does, however, support border-radius. A problem arises when you apply a filter to an element with border-radius. The filter overrides the border-radius and you lose your rounded corners.
> 
>  The most common problem is probably the equivalent of overflow: hidden whenever a filter is applied in IE6-7.

So the second problem isn't a problem for us. Even if it were, you can actually see what `overflow: visible` is not actually needed (simply extract it from your CSS and look at what happens). This is because we don't let an overflow happen.

The first problem, however, might be one if we were generally looking to provide border-radius. As such, I'll work on a fix for this. However, I suspect that the solution is actually to create an _outer_ container that sets a border radius rather than an inner container that inherits everything. The reason is that then we can avoid having to create special definitions in our stylesheet altogether, and in fact we could probably provide a class that always provides this piece of functionality. Won't know until I test though.

**Comment by ebollens** [comment]
Okay, I think I've got a solution to the problem that timmy willison describes for IE9.

You can find the implementation in `core/adapter/base/ie/fix_radius_gradient.js`...

``` js
Blocks.IE.fixRadiusGradient = function(ele){
    $(ele).each(function(){

        var y=['top','bottom'],
            x=['left','right'],
            i, j,
            props = [];

        for(i in x)
            for(j in y){
                var prop = 'border-'+y[j]+'-'+x[i]+'-radius',
                    value = $(this).css(prop)
                if(value != '0px')
                    props.push(prop+':'+value)
            }

        if(props.length > 0){
            if($(this).css('position') == 'fixed'){

                $(this).css('position', false)

                props.push('position:fixed')

                for(i in x){
                    var v = $(this).css(x[i])
                    if(v != 'auto')
                        props.push(x[i]+':'+v)
                }

                for(i in y){
                    var v = $(this).css(y[i])
                    if(v != 'auto')
                        props.push(y[i]+':'+v)
                }

            }

            $(this).wrap('<div style="'+props.join(';')+';overflow:hidden"></div>')
        }
    })
}
```

This hack is registered for the `nav.bar` element in `src/adapter/bootstrap/entity/nav/bar-ie.js`:

``` js
$(window).load(function(){
    Blocks.IE.fixRadiusGradient('nav.bar')
})
```

What this does is the following:
- Run only on IE browsers version 9 and less
- If a `nav.bar` has a border radius, then it creates a `div` that wraps `nav.bar`
- It applies the border radius values to this surrounding `div`, along with a `overflow:hidden` (per Timmy Willison's fix)
- If the element is `position:fixed`, then it moves those values into the surrounding div as well

Besides maybe improving the styling on the dropdown button and making the dropdown menu look nicer ( @atsengucla  would you like to take a pass at improving the appearance? let me know if you have any questions about the layout of the Bootstrap adapter file for it ), I'd say this is otherwise complete based on the prototype.html document that exists.

**Comment by ebollens** [comment]
I've closed this as functionality is complete, although @atsengucla or someone else may want to improve the styling of some of the features a bit.

**Comment by alicetseng** [comment]
sweet work @ebollens . Let me catch up on the masthead CSS and next color definitions. Since we're working in bits (and it's a bit more abstracted than I'm used to) -- I just need to finish these pieces and repull Rake to see how all the CSS comes together so I can wrap my head around it. 

I can take a second pass at styling once we have all Nav Family the parts/children defined (buttons,search,etc.). 

Let's open a separate ticket for CSS finessing and I can take that -- just ref against the ticket anything that's functional but needs polish. It tends to work better after the dependencies are complete so I'm not pre-maturely applying styles that will have other dependencies coming in.

**Comment by alicetseng** [comment]
OK CSS Polishing Ticket opened -- ref #129

**Comment by ebollens** [comment]
@atsengucla as na FYI, don't worry too much about what extends what from Bootstrap and stuff like that when doing the CSS-side mock. The spreadsheet you worked up was cool, but I couldn't take advantage of it quite as much as one would have thought - ultimately it was the example that was most valuable, so if you can work up those CSS examples, I can run from there directly :-)

**Comment by alicetseng** [comment]
@ebollens cool. that was super tedious to do. glad to chuck it. OK. straight in-browser mocks from now on.

**Comment by ebollens** [comment]
As a note on this one, I did not attach rounded corners as a default. However, if rounded corners are attached, it will automatically create a containing div that solves the IE9 problem. To test this, just create a `<nav class="bar" style="border-radius:10px">` and let me know if it does indeed work on IE - as I don't have that readily available.
