### ISSUE TITLE
Webblocks default styles

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#311]
So Webblocks adds things like `font-weight:bold` to `header` elements.  

Is there a reason for doing this? 

A way to turn that off or split that, so we get a better reset might be helpful for anyone not using standard fonts (just about every designer on the planet).  

There's also some other cases too.  I thought webblocks provided a user-agent reset, but it's unclear what is there and what isn't.  I'd really like a reset that strips everything.

@ebollens @chris4ucla

**Comment by ebollens** [comment]
The reason it is explicitly making them all bold is that the normlize.css reset provided in `src/core/adapter/base/_reset.scss` has an oversight: browsers differ in their implementation of header elements per their user agent style sheet.

Here's a list of some user agent style sheets:
http://meiert.com/en/blog/20070922/user-agent-style-sheets

If you look at that link, you can see that many apply `font-weight: bold` at the sheet level while others do not. Better than providing an inconsistent experience, WebBlocks decided to take a majority consensus opinion and thus use `font-weight:bold`. This should not preclude you from overriding with your own styles, even simply be doing:

``` css
h1, h2, h3, h4, h5, h6 {
    font-weight: normal;
}
```

Because WebBlocks does not to rearrangement of definitions, if this comes in your own sheet, it will win by order precedence.

We do not do a complete reset because, honestly, no one does a complete reset of everything. Instead, we try to choose coherent defaults. 

Would you like to have more configuration options though? I could provide one like `$type-font-header-weight` or even something like `$type-font-header-h1-weight`. Just like colors, if you defined `$type-font-header-weight: "normal"` and then `$type-font-header-h1-weight: "bold"`, you could target just the `h1` as bold and keep the others normal. Thoughts?

**Comment by lnicks** [comment]
The issue is less to do with the actual config and more to do with the consistency, normalization vs reset.  

I'm surprised to hear that no one uses complete resets.  I much prefer starting at a baseline, but that's my preference.  I don't mind a normalization, I just wasn't sure where it was coming from, and in this case why.  I have never built a site that didn't change the header font, so it was curious to me why the application of `font-weight`, when the header fonts are almost guaranteed to be different than a default to begin with.  But I might be nitpicky here though.

As far as config options go, I don't think the variables will help too much, I'm still adding my own 'reset', so it's just another way of writing it.   It's easier for me to blanket state that all headers are `font-size:normal`, and makes more sense from an inheritance point of view since the headers are not consistent across the site.  

So yeah, was looking for something closer to a complete reset rather than bit by bit.  

However a list of things that webblocks changes after normalize.css, might be useful.  A list of the 'coherent defaults'.  Sorry if I wasn't around for that conversation, doh!

**Comment by ebollens** [comment]
What it changes is completely dependent on the adapter you're using. 

If, for example, you're not using an adapter, then you get the following:
- `src/core/adapter/base/_reset.scss`
- `src/core/adapter/base/type/_font.scss`

However, if you're using the Bootstrap adapter, you additionally get all their normalization stuff, which is its own slew of things - many of which do the same things as we do such as bolding. I think you'll find few frameworks out there that don't give you a baseline like bolding header text.

If you're curious how your particular compile renders, you can actually see it pretty easy: just configure your `doc/index.html` file to use `link` and `script` tags that point at your live build rather than the pre-compiled one that they usually use to ensure consistency.

If you're just compiling WebBlocks straight, this would be as easy as:

``` html
<!DOCTYPE html>
<html lang="en">

    <head>

        <!-- ... -->

        <link rel="stylesheet" href="../build/css/blocks.css">
        <script type="text/javascript" src="../build/js/blocks.js"></script>

        <!--[if lte IE 9]>
        <link rel="stylesheet" href="../build/css/blocks-ie.css">
        <script type="text/javascript" src="../build/js/blocks-ie.js"></script>
        <![endif]-->

        <!-- ... -->

    </head>

    <body>

        <!-- ... -->

    </body>

</html>
```

In fact, looking at it right now, the `doc/index.html` file looks like it already points there. I'd actually intended for it to point at a pre-build variety so I need to fix that, but the approve above should let you point at your real assets. Then simply go to the `API/Base/Type` section and look at how things render. It details all the changes made.
