### ISSUE TITLE
Entity/Nav/List

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#64]
Development task for `entity/nav/list` prototype (prototype issue: #20)

**Comment by loganfranken** [comment]
I completed the basic implementation of this entity. I updated the prototype to (1) remove the `span` element as an option for a list header (as I don't quite remember why I thought that was necessary) and (2) allow for headers placed outside list items (which I would argue is the most semantic option).

I'll move onto implementing the "accordion" and "flyout" features. I ran out of time for this milestone so I'm shifting it the next one.

**Comment by loganfranken** [comment]
Just leaving myself a note to consider integrating the https://github.com/ebollens/efx engine into the implementation of the effects for the entity/nav/list instead of using straight jQuery.

**Comment by loganfranken** [comment]
Ran out of time, moving this to 0.1.105

**Comment by loganfranken** [comment]
Moving to next milestone

**Comment by loganfranken** [comment]
Just a note that I explored implementing the accordion effect using `efx` and I don't think it will work here (although it could in the future): we would be trading a small bit of jQuery code for several `data-*` and `id` attributes that would increase the workload for the WebBlocks Developer.

I really like the concept behind `efx`, though, and I think it would be wonderful if we could standardize implementations of these effects, so here's a summary of what would be needed to apply it here:
1. An accordion driver (based on the toggle driver with "slide"effect) that toggles the `.active` class on the trigger element
2. A standardized place for initializing `efx` on the page
3. An option to specify relative trigger-target patterns (for example, it would be cool if I could somehow specify `.list.accordion>li` as a trigger and the child `ul,ol` as a target without having to explicitly specify the relationship with `data-*` and `id` attributes)

1 and 2 are straightforward, but what do you think about 3 @ebollens?

**Comment by ebollens** [comment]
Well, initialization of effects on particular elements can all go into the WebBlocks entity's module subdirectory within `src`. For that matter, you can actually even add additional drivers this way if they're not already in Efx - since Efx is adapter-driven and just delegates responsibility for an effect to a driver that has registered with it.

On the note of the accordion, does the one in Efx already not work for you? Or are maybe we just on an old commit ID as far as the submodule in WebBlocks goes? You can find the details of the accordion driver here:
https://github.com/ebollens/efx/blob/master/src/driver/accordion.js
https://github.com/ebollens/efx/blob/master/demo/accordion.html

I think it would actually be pretty easy to allow someone to tap efx with a single piece of semantics. Efx is made to support any content arrangement, without a requirement on the way the structure is laid out, but if you know the structure, then you can get strict quickly. A line of Javascript should be able to lay in the `data-` attributes on the right elements and then initialize Efx around it.

**Comment by ebollens** [comment]
What's the status on this at this point?

**Comment by loganfranken** [comment]
Sending myself a note to post an update on the status of this tonight. It's sitting, partially implemented on my home computer.

**Comment by loganfranken** [comment]
So I've completed the "flyout" effect for the `entity/nav/list`. Honestly, the effect itself is a little messy and we may want to consider removing it unless we can harden the implementation. Since we need fixed widths for the absolutely positioned child lists, the code dynamically bases the width on the root list element.

To round off this entity, we need to do a couple things:
- Harden implementation of the "flyout" effect (the child lists sometimes appear stacked, for example)
- Update the "flyout" effect to convert to an accordion effect on smaller viewports
- Add core adapter styling and effects

If we decide that we don't want to implement the flyout effect, then this cuts down on the amount of remaining work considerably.

Work's going to continue to be pretty hectic for the next couple weeks or so, so if we want to complete this soon, then I would suggest assigning to someone other than me (sorry!).

**Comment by ebollens** [comment]
This has moved to 0.1.07 and we'll just compile with Bootstrap adapter for the moment.

**Comment by ebollens** [comment]
I'm closing this issue, as the effects are working correctly and I'm unsure why it is still open. If you believe this has been closed wrongly, please reopen and explain. Thanks!
