### ISSUE TITLE
Git Command Assumed in PATH

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#68]
This may not be an actual issue: when I was running the most recent build on Windows 7, it failed on me because it was expecting the `git` command to be available. I usually pop open a git shell to run `git` commands or use the wonderful GitHub Windows client, so I didn't have `git` in my PATH.

Once I added it, it went smoothly.

I'm wondering if it's just strange that I didn't have `git` in my PATH or if it's something we should highlight as a prerequisite?

**Comment by ebollens** [comment]
@loganfranken this seems to be a problem with the Windows package installer for Git, probably because it sets up its own specialized shell. In order to get around this, there is a configuration namespace `WebBlocks.config[:exec]` that lets you modify the execution string such as `WebBlocks.config[:exec][:git] = '/usr/bin/git'`.

This is mentioned in passing as part of the `/README.md` file under the Build > Prerequisites section:

> By default, the Rakefile executes these tools as though they are within the user search path. In the event that they reside elsewhere in the file system, the invoking commands should be specified within `Rakefile-configure.rb`.

More in depth documentation will follow as we actually solidify the architecture. However, for the moment, you can find a full list of configuration options here:

> https://github.com/ucla/WebBlocks/wiki/Architecture

Any configuration option listed in there can be set in `Rakefile-config.rb` to override the defaults listed there.

**Comment by loganfranken** [comment]
Ahh, thanks @ebollens. That paragraph in the README was what I was getting at (sorry I didn't see it before); and yes, the configuration file has been working wonderfully.
