### ISSUE TITLE
Entity/Button Prototype

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#72]

**Comment by loganfranken** [comment]
Some initial thoughts: https://github.com/ucla/WebBlocks/wiki/Entity-Button

**Comment by ebollens** [comment]
Posted my thoughts on wiki in response.

**Comment by ebollens** [comment]
As a note, this should follow the Color Strategy document rather than where we're at right now.

As such, I'm going to slide it back one milestone, since we need to lay in the color strategy first.

**Comment by loganfranken** [comment]
Hey @ebollens, it's up to you, but I think that, since we can refer to the color strategy in a generic way, the prototyping can be finished for the upcoming milestone with the actual implementation in the next milestone.

I just committed the prototype. I left out the Twitter Bootstrap "btn-block" class, but left in the size classes as they have been useful to me in my own projects.

Are we still going to create that "Needs Review" label? Either way, any feedback would be awesome.

**Comment by ebollens** [comment]
Oh, my bad, for some reason I felt like this was an implementation ticket even though it clearly says prototype. Yeah, makes complete sense to create a prototype anyways with a generic allowance for color strategy - since color strategy might change over time and the prototype of the button itself shouldn't.

And I've created the Needs Review label now. Sorry on the delay.

**Comment by loganfranken** [comment]
Unless anyone has any other suggestions, I'm going to close this issue and move it to implementation tomorrow morning.

**Comment by ebollens** [comment]
@loganfranken why are we using the `.button` class for the `button` and `input` elements? If we do that, then we should do the same for the `table` where we explicitly state `table.table`. Call this a stream on conscious, but actually I think I like using classes in all cases. It prevents us from taking over someone's intended styles. Let's discuss this issue here instead: #98 ... and for the time being, let's assert that your prototype above is correct (although we might tweak on it if #98 decides not to have class names required for styling).

**Comment by loganfranken** [comment]
Moved to development: #100
