### ISSUE TITLE
Update Entities Documentation

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#83]
During the last meeting, it was agreed that we should retrofit the entities documentation.

**Comment by loganfranken** [comment]
Let me run through and do some clean-up tomorrow (and move some into "Upcoming"):
https://github.com/ucla/WebBlocks/wiki/Entities

**Comment by loganfranken** [comment]
The list has been cleaned up and condensed down.

I added the entities I was more sure about to the "Upcoming" list (where anyone can now pick them up and start working on them) and left the entities I was less sure about (either because there may not be a need for an explicit entity or because it may not have a place in the framework) in "Possible."

This is what I was trying to achieve (create a list that could be used for assigning entities/chopping up milestones), so I'm going to go ahead and close this.
